version: '3.8'

services:
  web:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "8000:80"
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data: