version: '3.8'

services:
  web:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "8000:80"
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
